In [1]:
import pandas as pd
import sqlite3

In [2]:
conn=sqlite3.connect('inventory.db')

In [3]:
tables= pd.read_sql_query("select name from sqlite_master where type='table'",conn)
tables

              name
0  begin_inventory
1    end_inventory
2        purchases
3  purchase_prices
4            sales
5   vendor_invoice

In [4]:
pd.read_sql("select count(*) from sales",conn)

   count(*)
0  12825363

In [5]:
for table in tables['name']:
    print('-' * 50, table, '-' * 50)
    print('Count of records:',pd.read_sql(f"SELECT COUNT(*) AS count FROM {table}",conn)['count'].values[0])
    display(pd.read_sql(f"SELECT * FROM {table} LIMIT 5",conn))

-------------------------------------------------- begin_inventory --------------------------------------------------
Count of records: 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

-------------------------------------------------- end_inventory --------------------------------------------------
Count of records: 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

-------------------------------------------------- purchases --------------------------------------------------
Count of records: 2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

-------------------------------------------------- purchase_prices --------------------------------------------------
Count of records: 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- sales --------------------------------------------------
Count of records: 12825363

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

-------------------------------------------------- vendor_invoice --------------------------------------------------
Count of records: 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

In [6]:
pd.read_sql_query("select * from vendor_invoice", conn)

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None
...,...,...,...,...,...,...,...,...,...,...
5538,9622,WEIN BAUER INC,2025-01-06,13626,2024-12-21,2025-02-10,90,1563.00,8.60,None
5539,9625,WESTERN SPIRITS BEVERAGE CO,2025-01-10,13661,2024-12-23,2025-02-18,4617,37300.48,186.50,None
5540,3664,WILLIAM GRANT & SONS INC,2025-01-02,13643,2024-12-22,2025-02-04,9848,202815.78,932.95,None
5541,9815,WINE GROUP INC,2025-01-03,13602,2024-12-20,2025-02-08,24747,149007.56,819.54,None
5542,90058,ZORVINO VINEYARDS,2025-01-05,13574,2024-12-18,2025-02-12,437,3608.11,16.60,None

In [7]:
begin_inventory = pd.read_sql("SELECT * FROM begin_inventory", conn)
end_inventory = pd.read_sql("SELECT * FROM end_inventory", conn)
purchases = pd.read_sql("SELECT * FROM purchases", conn)
purchase_prices = pd.read_sql("SELECT * FROM purchase_prices", conn)
sales = pd.read_sql("SELECT * FROM sales", conn)
vendor_invoice = pd.read_sql("SELECT * FROM vendor_invoice", conn)

In [8]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='object')

In [11]:
sales.groupby('Brand')[['SalesDollars','SalesPrice','SalesQuantity']].sum()

       SalesDollars  SalesPrice  SalesQuantity
Brand
58         43341.54    28145.64           3446
60         18716.25    10720.79           1775
61          4364.88      363.74            312
62        119863.75    90154.51           3125
63        112249.22    88553.10           2778
...             ...         ...            ...
90089      19078.41     5759.52            159
90090       9749.85     4549.93             15
90604       9119.24     2639.78             76
90609       2074.17     1774.29             83
90631      31504.41    19502.73           1659

[11237 rows x 3 columns]

In [12]:
purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2372469,49_GARIGILL_22298,49,22298,Zorvino Vyds Sangiovese,750mL,90058,ZORVINO VINEYARDS,13593,2024-12-19,2024-12-28,2025-01-09,2025-02-06,8.06,12,96.72,2
2372470,1_HARDERSFIELD_19556,1,19556,Zorvino Bacca Z Blackberry,750mL,90058,ZORVINO VINEYARDS,13593,2024-12-19,2024-12-27,2025-01-09,2025-02-06,9.39,12,112.68,2
2372471,66_EANVERNESS_22297,66,22297,Zorvino Vyds Pearz,750mL,90058,ZORVINO VINEYARDS,13593,2024-12-19,2024-12-26,2025-01-09,2025-02-06,6.75,12,81.00,2
2372472,69_MOUNTMEND_19557,69,19557,Zorvino Fragole Z Strawberry,750mL,90058,ZORVINO VINEYARDS,13593,2024-12-19,2024-12-26,2025-01-09,2025-02-06,9.39,12,112.68,2
2372473,55_DRY GULCH_22298,55,22298,Zorvino Vyds Sangiovese,750mL,90058,ZORVINO VINEYARDS,13593,2024-12-19,2024-12-28,2025-01-09,2025-02-06,8.06,12,96.72,2

In [26]:
purchase_prices.head()

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

In [14]:
end_inventory

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31
...,...,...,...,...,...,...,...,...,...
224484,81_PEMBROKE_90087,81,PEMBROKE,90087,Ch Mouton Rothschild 12 Paui,750mL,3,469.99,2024-12-31
224485,81_PEMBROKE_90088,81,PEMBROKE,90088,Ch Le Petite Mouton 12 Pauil,750mL,3,134.99,2024-12-31
224486,81_PEMBROKE_90089,81,PEMBROKE,90089,Ch Lynch Bages 12 Pauillac,750mL,3,119.99,2024-12-31
224487,81_PEMBROKE_90090,81,PEMBROKE,90090,Ch Lafite Rothschild 12,750mL,3,649.99,2024-12-31
224488,81_PEMBROKE_90604,81,PEMBROKE,90604,Ch Lynch Bages Pauilac,750mL,2,119.99,2024-12-31

In [19]:
end_inventory.groupby('Brand')[['Price']].sum()

         Price
Brand
58      532.59
60      175.84
61       13.99
62     2700.27
63     2729.30
...        ...
90089  1079.91
90090  3899.94
90604   719.94
90609   249.90
90631   455.76

[9653 rows x 1 columns]

In [21]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='object')

In [24]:
frieght_ssummary = pd.read_sql_query ("""select VendorNumber,SUM(Freight) as FrieghtCost 
from vendor_invoice group by VendorNumber""",conn)

In [25]:
frieght_ssummary

     VendorNumber  FrieghtCost
0               2        27.08
1              54         0.48
2              60       367.52
3             105        62.39
4             200         6.19
..            ...          ...
121         98450       856.02
122         99166       130.09
123        172662       178.34
124        173357       202.50
125        201359         0.09

[126 rows x 2 columns]

In [31]:
 purchase_summary = pd.read_sql_query("""
SELECT
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.PurchasePrice,
    pp.Volume,
    pp.Price AS ActualPrice,
    SUM(p.Quantity) AS TotalPurchaseQuantity,
    SUM(p.Dollars) AS TotalPurchaseDollars
FROM purchases p
JOIN purchase_prices pp
    ON p.Brand = pp.Brand
    where p.PurchasePrice>0
GROUP BY
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.PurchasePrice,
    pp.Volume,
    pp.Price
ORDER BY TotalPurchaseDollars DESC;
""", conn)

In [30]:
purchase_summary

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars
0,1128,BROWN-FORMAN CORP,1233,26.27,1750,36.99,145080,3811251.60
1,4425,MARTIGNETTI COMPANIES,3405,23.19,1750,28.99,164038,3804041.22
2,17035,PERNOD RICARD USA,8068,18.24,1750,24.99,187407,3418303.68
3,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750,22.99,201682,3261197.94
4,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750,29.99,138109,3023206.01
...,...,...,...,...,...,...,...,...
10688,8004,SAZERAC CO INC,5683,0.39,50,0.49,6,2.34
10689,3924,HEAVEN HILL DISTILLERIES,9123,0.74,50,0.99,2,1.48
10690,3960,DIAGEO NORTH AMERICA INC,6127,1.47,200,1.99,1,1.47
10691,7245,PROXIMO SPIRITS INC.,3065,0.71,50,0.99,1,0.71
10692,2561,EDRINGTON AMERICAS,2166,0.00,750,0.00,2015,0.00

In [32]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='object')

In [36]:
sales_summary = pd.read_sql_query("""
SELECT
    VendorNo,
    Brand,
    SUM(SalesDollars) AS TotalSalesDollars,
    SUM(SalesPrice) AS TotalSalesPrice,
    SUM(SalesQuantity) AS TotalSalesQuantity,
    SUM(ExciseTax) AS TotalExciseTax
FROM sales
GROUP BY
    VendorNo,
    Brand
ORDER BY
    TotalSalesPrice;
""", conn)

sales_summary.head()

,VendorNo,Brand,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax
0,8004,5341,5.39,0.49,11,0.58
1,8004,5287,0.98,0.98,2,0.10
2,3252,3933,1.98,0.99,2,0.10
3,3924,9123,1.98,0.99,2,0.10
4,9206,2773,0.99,0.99,1,0.05

In [ ]:
CREATE TABLE sales_summary AS
SELECT
    VendorNo,
    Brand,
    SUM(SalesQuantity) AS TotalSalesQuantity,
    SUM(SalesDollars) AS TotalSalesDollars,
    SUM(SalesPrice) AS TotalSalesPrice,
    SUM(ExciseTax) AS TotalExciseTax
FROM sales
GROUP BY VendorNo, Brand;

In [ ]:
CREATE TABLE vendor_summary AS
SELECT
    VendorNumber,
    SUM(Quantity) AS TotalPurchaseQuantity,
    SUM(Dollars) AS TotalPurchaseDollars,
    SUM(Freight) AS TotalFreightCost
FROM vendor_invoice
GROUP BY VendorNumber;

In [ ]:
CREATE INDEX idx_sales_summary
ON sales_summary(VendorNo, Brand);

CREATE INDEX idx_vendor_summary
ON vendor_summary(VendorNumber);

CREATE INDEX idx_purchase_prices
ON purchase_prices(VendorNumber, Brand);

In [ ]:
final_table = pd.read_sql_query("""
SELECT
    pp.VendorNumber,
    pp.Brand,
    pp.Price,
    pp.PurchasePrice,
    ss.TotalSalesQuantity,
    ss.TotalSalesDollars,
    ss.TotalSalesPrice,
    ss.TotalExciseTax,
    vs.TotalPurchaseQuantity,
    vs.TotalPurchaseDollars,
    vs.TotalFreightCost
FROM purchase_prices pp
LEFT JOIN sales_summary ss
ON pp.VendorNumber = ss.VendorNo
AND pp.Brand = ss.Brand
LEFT JOIN vendor_summary vs
ON pp.VendorNumber = vs.VendorNumber;
""", conn)

In [ ]:
final_table.head()

In [7]:
pd.read_sql_query("SELECT COUNT(*) FROM sales;", conn)

   COUNT(*)
0  12825363

In [5]:
pd.read_sql_query("SELECT COUNT(*) FROM purchase_prices;", conn)

   COUNT(*)
0     12261

In [6]:
pd.read_sql_query("SELECT COUNT(*) FROM vendor_invoice;", conn)

   COUNT(*)
0      5543

In [2]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("inventory.db")

In [3]:
pd.read_sql_query("SELECT 1;", conn)

   1
0  1

In [4]:
pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

              name
0  begin_inventory
1    end_inventory
2        purchases
3  purchase_prices
4            sales
5   vendor_invoice

In [8]:
pd.read_sql_query("PRAGMA index_list('sales');", conn)

Empty DataFrame
Columns: [seq, name, unique, origin, partial]
Index: []

In [9]:
pd.read_sql_query("""
SELECT COUNT(*) AS rows,
       COUNT(DISTINCT VendorNo || '-' || Brand) AS unique_vendor_brand
FROM sales;
""", conn)

       rows  unique_vendor_brand
0  12825363                11272

In [11]:
pip install duckdb

Defaulting to user installation because normal site-packages is not writeable
Collecting duckdb
  Downloading duckdb-1.5.5-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Downloading duckdb-1.5.5-cp313-cp313-win_amd64.whl (13.2 MB)
   ---------------------------------------- 0.0/13.2 MB ? eta -:--:--
   --- ------------------------------------ 1.3/13.2 MB 14.6 MB/s eta 0:00:01
   ------------ --------------------------- 4.2/13.2 MB 15.5 MB/s eta 0:00:01
   ---------------------- ----------------- 7.3/13.2 MB 15.1 MB/s eta 0:00:01
   --------------------------------- ------ 11.0/13.2 MB 15.6 MB/s eta 0:00:01
   ---------------------------------------- 13.2/13.2 MB 15.9 MB/s  0:00:00
Installing collected packages: duckdb
Successfully installed duckdb-1.5.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
import duckdb

In [13]:
duck = duckdb.connect()

duck.execute("INSTALL sqlite;")
duck.execute("LOAD sqlite;")

duck.execute("ATTACH 'inventory.db' AS inv (TYPE SQLITE);")

In [15]:
sales = duck.sql("""
SELECT * FROM inv.sales
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [16]:
sales_summary = duck.sql("""
SELECT
    VendorNo,
    Brand,
    SUM(SalesQuantity) AS TotalSalesQuantity,
    SUM(SalesDollars) AS TotalSalesDollars,
    SUM(SalesPrice) AS TotalSalesPrice,
    SUM(ExciseTax) AS TotalExciseTax
FROM inv.sales
GROUP BY VendorNo, Brand
""").df()

In [17]:
type(sales)

pandas.core.frame.DataFrame

In [18]:
sales.shape

(12825363, 14)

In [19]:
sales_summary

,VendorNo,Brand,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax
0,8664,3039,4277.0,77290.23,48240.39,3370.02
1,7245,3183,3451.0,66976.49,55898.77,2721.73
2,11567,3189,2987.0,36431.13,27716.55,2354.88
3,8673,32107,2255.0,29922.45,17191.08,250.46
4,8112,3233,1304.0,30166.96,22594.24,1027.93
...,...,...,...,...,...,...
11267,4425,15091,12.0,311.88,25.99,1.35
11268,9165,14347,1.0,13.99,13.99,0.11
11269,9552,38830,1.0,169.99,169.99,0.11
11270,3951,27566,3.0,125.97,125.97,0.33
11271,10754,28050,4.0,67.96,33.98,0.45

In [20]:
duck.sql("""
SHOW TABLES FROM inv;
""").df()

              name
0  begin_inventory
1    end_inventory
2  purchase_prices
3        purchases
4            sales
5   vendor_invoice

In [21]:
sales_summary = duck.sql("""
SELECT
    VendorNo,
    Brand,
    SUM(SalesQuantity) AS TotalSalesQuantity,
    SUM(SalesDollars) AS TotalSalesDollars,
    SUM(SalesPrice) AS TotalSalesPrice,
    SUM(ExciseTax) AS TotalExciseTax
FROM inv.sales
GROUP BY VendorNo, Brand
""").df()

sales_summary.head()

,VendorNo,Brand,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax
0,8892,41033,5842.0,55806.58,30154.48,649.51
1,9819,41251,17896.0,97451.04,32928.74,2004.53
2,660,4181,16430.0,189110.70,105768.26,30190.64
3,1485,4224,13082.0,212285.18,122716.60,10304.54
4,480,4252,9958.0,9858.42,3051.18,516.74

In [22]:
vendor_summary = duck.sql("""
SELECT
    VendorNumber,
    SUM(Quantity) AS TotalPurchaseQuantity,
    SUM(Dollars) AS TotalPurchaseDollars,
    SUM(Freight) AS TotalFreightCost
FROM inv.vendor_invoice
GROUP BY VendorNumber
""").df()

vendor_summary.head()

   VendorNumber  TotalPurchaseQuantity  TotalPurchaseDollars  TotalFreightCost
0           388                 1847.0              41116.32            211.74
1          8352               283260.0            2051436.01          10261.60
2          6359               110162.0             387622.69           1922.00
3          7255                16493.0             128895.69            648.71
4          3951                  372.0               5500.32             29.43

In [23]:
purchase_prices = duck.sql("""
SELECT *
FROM inv.purchase_prices
""").df()

purchase_prices.head()

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

In [26]:
vendor_sales_summary = (
    purchase_prices
    .merge(
        sales_summary,
        left_on=["VendorNumber", "Brand"],
        right_on=["VendorNo", "Brand"],
        how="left"
    )
    .merge(
        vendor_summary,
        on="VendorNumber",
        how="left"
    )
)
vendor_sales_summary.head()

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName,VendorNo,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,TotalPurchaseQuantity,TotalPurchaseDollars,TotalFreightCost
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD,8320.0,3446.0,43341.54,28145.64,2715.12,69127.0,624979.64,3151.92
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP,1128.0,3125.0,119863.75,90154.51,2463.18,1006122.0,13529433.08,68601.68
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP,1128.0,2778.0,112249.22,88553.10,2190.45,1006122.0,13529433.08,68601.68
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP,9165.0,469.0,17325.31,12626.57,369.84,1077527.0,13210613.93,68054.70
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.,7245.0,21.0,314.79,134.91,16.53,682042.0,7588029.90,38994.78

In [57]:
duck.sql("""
DESCRIBE inv.purchase_prices;
""").df()

      column_name column_type null   key default extra
0           Brand      BIGINT  YES  None    None  None
1     Description     VARCHAR  YES  None    None  None
2           Price      DOUBLE  YES  None    None  None
3            Size     VARCHAR  YES  None    None  None
4          Volume     VARCHAR  YES  None    None  None
5  Classification      BIGINT  YES  None    None  None
6   PurchasePrice      DOUBLE  YES  None    None  None
7    VendorNumber      BIGINT  YES  None    None  None
8      VendorName     VARCHAR  YES  None    None  None

In [27]:
vendor_sales_summary.shape

(12261, 17)

In [58]:
duck.sql("""
DESCRIBE inv.purchases;
""").df()

       column_name column_type null   key default extra
0      InventoryId     VARCHAR  YES  None    None  None
1            Store      BIGINT  YES  None    None  None
2            Brand      BIGINT  YES  None    None  None
3      Description     VARCHAR  YES  None    None  None
4             Size     VARCHAR  YES  None    None  None
5     VendorNumber      BIGINT  YES  None    None  None
6       VendorName     VARCHAR  YES  None    None  None
7         PONumber      BIGINT  YES  None    None  None
8           PODate     VARCHAR  YES  None    None  None
9    ReceivingDate     VARCHAR  YES  None    None  None
10     InvoiceDate     VARCHAR  YES  None    None  None
11         PayDate     VARCHAR  YES  None    None  None
12   PurchasePrice      DOUBLE  YES  None    None  None
13        Quantity      BIGINT  YES  None    None  None
14         Dollars      DOUBLE  YES  None    None  None
15  Classification      BIGINT  YES  None    None  None

In [59]:
duck.sql("""
SELECT *
FROM inv.purchase_prices
LIMIT 10;
""").df()

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.
5,77,Three Olives Espresso Vodka,12.99,750mL,750,1,10.39,7245,PROXIMO SPIRITS INC.
6,79,Three Olives Loopy Vodka,14.99,750mL,750,1,9.62,7245,PROXIMO SPIRITS INC.
7,115,Belvedere Vodka,27.99,1000mL,1000,1,21.37,8112,MOET HENNESSY USA INC
8,126,Grey Goose Vodka,32.99,1000mL,1000,1,20.14,480,BACARDI USA INC
9,168,Three Olives Strawberry,12.99,750mL,750,1,8.95,7245,PROXIMO SPIRITS INC.

In [60]:
duck.sql("""
SELECT
    Brand,
    COUNT(*) AS cnt
FROM inv.purchase_prices
GROUP BY Brand
HAVING COUNT(*) > 1
ORDER BY cnt DESC
LIMIT 20;
""").df()

Empty DataFrame
Columns: [Brand, cnt]
Index: []

In [61]:
duck.sql("""
SELECT COUNT(*)
FROM inv.purchases;
""").df()

   count_star()
0       2372474

In [62]:
duck.sql("""
SELECT COUNT(*)
FROM inv.purchases p
JOIN inv.purchase_prices pp
ON p.Brand = pp.Brand;
""").df()

   count_star()
0       2372474

In [63]:
duck.sql("""
SELECT
    VendorNumber,
    COUNT(*) AS Brands
FROM inv.purchase_prices
GROUP BY VendorNumber
HAVING COUNT(*) > 1
ORDER BY Brands DESC
LIMIT 20;
""").df()

    VendorNumber  Brands
0           4425    1639
1           9165     965
2           9552     960
3          10754     897
4           3252     527
5           1392     481
6           7153     480
7           3960     449
8           2000     417
9          12546     415
10         17035     277
11           653     258
12          4692     242
13          9815     215
14         90024     206
15           480     184
16          6785     174
17         90047     165
18          8892     153
19          9744     149

In [64]:
duck.sql("""
SELECT SUM(Dollars)
FROM inv.vendor_invoice;
""").df()

   sum(Dollars)
0  3.219008e+08

In [65]:
duck.sql("""
SELECT SUM(TotalPurchaseDollars)
FROM inv.vendor_sales_summary;
""").df()

   sum(TotalPurchaseDollars)
0               1.461216e+11

In [66]:
vendor_sales_summary = duck.sql("""
WITH PurchaseSummary AS (
    SELECT
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.Description,
        p.PurchasePrice,
        pp.Price AS ActualPrice,
        pp.Volume,
        SUM(p.Quantity) AS TotalPurchaseQuantity,
        SUM(p.Dollars) AS TotalPurchaseDollars
    FROM inv.purchases p
    JOIN inv.purchase_prices pp
        ON p.Brand = pp.Brand
    WHERE p.PurchasePrice > 0
    GROUP BY
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.Description,
        p.PurchasePrice,
        pp.Price,
        pp.Volume
),

SalesSummary AS (
    SELECT
        VendorNo,
        Brand,
        SUM(SalesQuantity) AS TotalSalesQuantity,
        SUM(SalesDollars) AS TotalSalesDollars,
        SUM(SalesPrice) AS TotalSalesPrice,
        SUM(ExciseTax) AS TotalExciseTax
    FROM inv.sales
    GROUP BY VendorNo, Brand
),

FreightSummary AS (
    SELECT
        VendorNumber,
        SUM(Freight) AS FreightCost
    FROM inv.vendor_invoice
    GROUP BY VendorNumber
)

SELECT
    ps.VendorNumber,
    ps.VendorName,
    ps.Brand,
    ps.Description,
    ps.PurchasePrice,
    ps.ActualPrice,
    ps.Volume,
    ps.TotalPurchaseQuantity,
    ps.TotalPurchaseDollars,

    COALESCE(ss.TotalSalesQuantity,0) AS TotalSalesQuantity,
    COALESCE(ss.TotalSalesDollars,0) AS TotalSalesDollars,
    COALESCE(ss.TotalSalesPrice,0) AS TotalSalesPrice,
    COALESCE(ss.TotalExciseTax,0) AS TotalExciseTax,

    COALESCE(fs.FreightCost,0) AS FreightCost

FROM PurchaseSummary ps

LEFT JOIN SalesSummary ss
    ON ps.VendorNumber = ss.VendorNo
   AND ps.Brand = ss.Brand

LEFT JOIN FreightSummary fs
    ON ps.VendorNumber = fs.VendorNumber

ORDER BY ps.TotalPurchaseDollars DESC;
""").df()

In [67]:
vendor_sales_summary.shape

(10692, 14)

In [68]:
duck.sql("""
WITH PurchaseSummary AS (
    SELECT
        p.VendorNumber,
        p.Brand,
        SUM(p.Dollars) AS TotalPurchaseDollars
    FROM inv.purchases p
    JOIN inv.purchase_prices pp
        ON p.Brand = pp.Brand
    WHERE p.PurchasePrice > 0
    GROUP BY
        p.VendorNumber,
        p.Brand
)
SELECT SUM(TotalPurchaseDollars)
FROM PurchaseSummary;
""").df()

   sum(TotalPurchaseDollars)
0               3.219008e+08

In [69]:
duck.sql("""
WITH PurchaseSummary AS (
    SELECT
        p.VendorNumber,
        p.Brand,
        SUM(p.Dollars) AS TotalPurchaseDollars
    FROM inv.purchases p
    JOIN inv.purchase_prices pp
        ON p.Brand = pp.Brand
    WHERE p.PurchasePrice > 0
    GROUP BY
        p.VendorNumber,
        p.Brand
),

SalesSummary AS (
    SELECT
        VendorNo,
        Brand,
        SUM(SalesDollars) AS TotalSalesDollars
    FROM inv.sales
    GROUP BY VendorNo, Brand
)

SELECT COUNT(*)
FROM PurchaseSummary ps
LEFT JOIN SalesSummary ss
ON ps.VendorNumber = ss.VendorNo
AND ps.Brand = ss.Brand;
""").df()

   count_star()
0         10692

In [70]:
duck.sql("""
WITH PurchaseSummary AS (
    SELECT
        p.VendorNumber,
        p.Brand,
        SUM(p.Dollars) AS TotalPurchaseDollars
    FROM inv.purchases p
    JOIN inv.purchase_prices pp
        ON p.Brand = pp.Brand
    WHERE p.PurchasePrice > 0
    GROUP BY
        p.VendorNumber,
        p.Brand
),

FreightSummary AS (
    SELECT
        VendorNumber,
        SUM(Freight) AS FreightCost
    FROM inv.vendor_invoice
    GROUP BY VendorNumber
)

SELECT COUNT(*)
FROM PurchaseSummary ps
LEFT JOIN FreightSummary fs
ON ps.VendorNumber = fs.VendorNumber;
""").df()

   count_star()
0         10692

In [28]:
vendor_sales_summary.dtypes

Brand                      int64
Description               object
Price                    float64
Size                      object
Volume                    object
Classification             int64
PurchasePrice            float64
VendorNumber               int64
VendorName                object
VendorNo                 float64
TotalSalesQuantity       float64
TotalSalesDollars        float64
TotalSalesPrice          float64
TotalExciseTax           float64
TotalPurchaseQuantity    float64
TotalPurchaseDollars     float64
TotalFreightCost         float64
dtype: object

In [72]:
duck.sql("""
SELECT COUNT(*)
FROM inv.vendor_sales_summary;
""").df()

   count_star()
0         12261

In [73]:
duck.register("vendor_sales_summary_df", vendor_sales_summary)

duck.sql("""
CREATE OR REPLACE TABLE inv.vendor_sales_summary AS
SELECT *
FROM vendor_sales_summary_df;
""")

In [74]:
duck.sql("""
SELECT SUM(TotalPurchaseDollars)
FROM inv.vendor_sales_summary;
""").df()

   sum(TotalPurchaseDollars)
0               3.219008e+08

In [71]:
vendor_sales_summary["TotalPurchaseDollars"].sum()

np.float64(321900765.5300001)

In [30]:
vendor_sales_summary.isnull().sum()

Brand                       0
Description                 1
Price                       0
Size                        1
Volume                      1
Classification              0
PurchasePrice               0
VendorNumber                0
VendorName                  0
VendorNo                 1036
TotalSalesQuantity       1036
TotalSalesDollars        1036
TotalSalesPrice          1036
TotalExciseTax           1036
TotalPurchaseQuantity       6
TotalPurchaseDollars        6
TotalFreightCost            6
dtype: int64

In [46]:
vendor_sales_summary['VendorName'].unique()

array(['SHAW ROSS INT L IMP LTD', 'BROWN-FORMAN CORP',
       'ULTRA BEVERAGE COMPANY LLP', 'PROXIMO SPIRITS INC.',
       'MOET HENNESSY USA INC', 'BACARDI USA INC',
       'JIM BEAM BRANDS COMPANY', 'CAMPARI AMERICA',
       'WILLIAM GRANT & SONS INC', 'MARTIGNETTI COMPANIES',
       'CONSTELLATION BRANDS INC', 'M S WALKER INC',
       'DIAGEO NORTH AMERICA INC', 'MCCORMICK DISTILLING CO',
       'PERNOD RICARD USA', 'PINE STATE TRADING CO',
       'STATE WINE & SPIRITS', 'DISARONNO INTERNATIONAL LLC',
       'SAZERAC CO INC', 'PERFECTA WINES', 'HEAVEN HILL DISTILLERIES',
       'LABELLE VYDS AND WINERY', 'REMY COINTREAU USA INC',
       'SIDNEY FRANK IMPORTING CO', 'MHW LTD', 'PHILLIPS PRODUCTS CO.',
       'LUXCO INC', 'WESTERN SPIRITS BEVERAGE CO', 'CASTLE BRANDS CORP.',
       'SAZERAC NORTH AMERICA INC.', 'OLE SMOKY DISTILLERY LLC',
       'STOLI GROUP,(USA) LLC', 'SMOKY QUARTZ DISTILLERY LLC',
       'VINEDREA WINES LLC', 'EDRINGTON AMERICAS',
       'DUGGANS DISTILLED PRODUCTS', 'PALM BAY INTERNATIONAL INC',
       'E & J GALLO WINERY', 'FLAG HILL WINERY & VINEYARD',
       'FREDERICK WILDMAN & SONS', 'BULLY BOY DISTILLERS',
       'DJINN SPIRITS LLC', 'THE PIERPONT GROUP LLC',
       'STAR INDUSTRIES INC.', 'TY KU LLC', 'Serralles Usa LLC',
       'SEA HAGG DISTILLERY LLC', 'WHYTE & MACKAY',
       'SOUTHERN WINE & SPIRITS NE', 'Mizkan Americas, Inc.',
       'Russian Standard Vodka', 'BLACK PRINCE DISTILLERY INC',
       'KLIN SPIRITS LLC', 'MARSALLE COMPANY',
       'CHARLES JACQUIN ET CIE INC', 'KOBRAND CORPORATION',
       'WINE GROUP INC', 'FABRIZIA SPIRITS LLC', 'LAIRD & CO',
       'AMERICAN VINTAGE BEVERAGE', 'NICHE W & S',
       'STE MICHELLE WINE ESTATES', 'BANFI PRODUCTS CORP',
       'TRINCHERO FAMILY ESTATES', 'DIAGEO CHATEAU ESTATE WINES',
       'MAJESTIC FINE WINES', 'TREASURY WINE ESTATES',
       'VINEYARD BRANDS INC', 'PREMIER DISTRIBUTORS',
       'PREMIUM PORT WINES, INC.', 'ALTAMAR BRANDS LLC',
       'TAKARA SAKE USA INC', 'DELICATO VINEYARDS INC', 'VINILANDIA USA',
       'THE IMPORTED GRAPE LLC', 'CANDIA VINEYARDS', 'CRUSH WINES',
       'LATITUDE BEVERAGE COMPANY', 'POVERTY LANE ORCHARDS',
       'MOONLIGHT MEADERY', 'SURVILLE ENTERPRISES CORP',
       'SWEET BABY VINEYARD', 'VINEXTRA INC', 'STELLAR IMPORTING CO LLC',
       'VRANKEN AMERICA', 'JEWELL TOWNE VINEYARDS',
       'HAUNTING WHISPER VYDS', 'ZORVINO VINEYARDS', 'R.P.IMPORTS INC',
       'PSP WINES', 'MILTONS DISTRIBUTING CO', 'SEA BREEZE CELLARS LLC',
       'SILVER MOUNTAIN CIDERS', 'FORTUNE WINE BROKERS LLC',
       'FANTASY FINE WINES CORP', 'PARK STREET IMPORTS LLC',
       'CAPSTONE INTERNATIONAL', 'CALEDONIA SPIRITS INC',
       'WEIN BAUER INC', 'INCREDIBREW INC', 'ADAMBA IMPORTS INTL INC',
       'Circa Wines', 'TALL SHIP DISTILLERY LLC', 'ALISA CARR BEVERAGES',
       'CENTEUR IMPORTS LLC', 'BLACK ROCK SPIRITS LLC', 'HALO DISTILLERY',
       'Dunn Wine Brokers', 'FULCHINO VINEYARD INC',
       'AMERICAN SPIRITS EXCHANGE', 'LAUREATE IMPORTS CO', 'UNCORKED',
       'HOOD RIVER DISTILLERS, Inc.', 'BERNIKO LLC',
       'IRA GOLDMAN AND WILLIAMS, LLP', 'BRONCO WINE COMPANY',
       'FLEMISH LION LLC', 'EXCLUSIVE WINES & SPIRITS',
       'MANGO BOTTLING INC', 'APPOLO VINEYARDS LLC',
       'WALPOLE MTN VIEW WINERY', 'ATLANTIC IMPORTING COMPANY',
       'HIGHLAND WINE MERCHANTS LLC', 'TAMWORTH DISTILLING',
       'SWEETWATER FARM', 'STARK BREWING COMPANY', 'TRUETT HURST',
       'SOUTHERN GLAZERS W&S OF NE', 'GILMANTON WINERY & VINEYARD',
       'AAPER ALCOHOL & CHEMICAL CO', 'BLACK COVE BEVERAGES',
       'LOYAL DOG WINERY', 'VINEYARD BRANDS LLC'], dtype=object)

In [36]:
vendor_sales_summary['Description'].unique()

array(['Gekkeikan Black & Gold Sake', 'Herradura Silver Tequila',
       'Herradura Reposado Tequila', ..., 'Sanford Santa Rita Pnt Nr',
       'Neal One Lane Bridg Cab Svgn', 'Calera Viognier Mt Harlan'],
      shape=(11115,), dtype=object)

In [40]:
vendor_sales_summary["Volume"] = pd.to_numeric(
    vendor_sales_summary["Volume"],
    errors="coerce"
)

In [42]:
vendor_sales_summary.fillna(0, inplace=True)

In [43]:
vendor_sales_summary["VendorName"] = vendor_sales_summary["VendorName"].str.strip()

In [76]:
vendor_sales_summary["GrossProfit"] = (
    vendor_sales_summary["TotalSalesDollars"]
    - vendor_sales_summary["TotalPurchaseDollars"]
)

vendor_sales_summary["ProfitMargin"] = (
    vendor_sales_summary["GrossProfit"]
    / vendor_sales_summary["TotalSalesDollars"]
) * 100

vendor_sales_summary["StockTurnover"] = (
    vendor_sales_summary["TotalSalesQuantity"]
    / vendor_sales_summary["TotalPurchaseQuantity"]
)

vendor_sales_summary["SalesToPurchaseRatio"] = (
    vendor_sales_summary["TotalSalesDollars"]
    / vendor_sales_summary["TotalPurchaseDollars"]
)

In [77]:
vendor_sales_summary.columns

Index(['VendorNumber', 'VendorName', 'Brand', 'Description', 'PurchasePrice',
       'ActualPrice', 'Volume', 'TotalPurchaseQuantity',
       'TotalPurchaseDollars', 'TotalSalesQuantity', 'TotalSalesDollars',
       'TotalSalesPrice', 'TotalExciseTax', 'FreightCost', 'GrossProfit',
       'ProfitMargin', 'StockTurnover', 'SalesToPurchaseRatio'],
      dtype='object')

In [49]:
vendor_sales_summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12261 entries, 0 to 12260
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Brand                  12261 non-null  int64
 1   Description            12261 non-null  object
 2   Price                  12261 non-null  float64
 3   Size                   12261 non-null  object
 4   Volume                 12261 non-null  float64
 5   Classification         12261 non-null  int64
 6   PurchasePrice          12261 non-null  float64
 7   VendorNumber           12261 non-null  int64
 8   VendorName             12261 non-null  object
 9   VendorNo               12261 non-null  float64
 10  TotalSalesQuantity     12261 non-null  float64
 11  TotalSalesDollars      12261 non-null  float64
 12  TotalSalesPrice        12261 non-null  float64
 13  TotalExciseTax         12261 non-null  float64
 14  TotalPurchaseQuantity  12261 non-null  float64
 15  TotalPurchaseDollars   12261 non-null  float64
 16  TotalFreightCost       12261 non-null  float64
 17  GrossProfit            12261 non-null  float64
 18  ProfitMargin           12258 non-null  float64
 19  StockTurnover          12258 non-null  float64
 20  SalestoPurchaseRatio   12258 non-null  float64
dtypes: float64(15), int64(3), object(3)
memory usage: 2.0+ MB

In [50]:
vendor_sales_summary.replace([np.inf, -np.inf], 0, inplace=True)
vendor_sales_summary.fillna(0, inplace=True)

In [51]:
cursor=conn.cursor()

In [53]:
cursor.execute("""
CREATE TABLE vendor_sales_summary (
    VendorNumber INT,
    VendorName VARCHAR(100),
    Brand INT,
    Description VARCHAR(100),
    PurchasePrice DECIMAL(10,2),
    ActualPrice DECIMAL(10,2),
    Volume INT,
    TotalPurchaseQuantity INT,
    TotalPurchaseDollars DECIMAL(15,2),
    TotalSalesQuantity INT,
    TotalSalesDollars DECIMAL(15,2),
    TotalSalesPrice DECIMAL(15,2),
    TotalExciseTax DECIMAL(15,2),
    FreightCost DECIMAL(15,2),
    GrossProfit DECIMAL(15,2),
    ProfitMargin DECIMAL(15,2),
    StockTurnover DECIMAL(15,2),
    SalesToPurchaseRatio DECIMAL(15,2),
    PRIMARY KEY (VendorNumber, Brand)
);
""")

In [56]:
pd.read_sql("select * from vendor_sales_summary",conn)

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName,VendorNo,...,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,TotalPurchaseQuantity,TotalPurchaseDollars,TotalFreightCost,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750.0,1,9.28,8320,SHAW ROSS INT L IMP LTD,8320.0,...,43341.54,28145.64,2715.12,69127.0,624979.64,3151.92,-581638.10,-1.341988e+03,0.049850,0.069349
1,62,Herradura Silver Tequila,36.99,750mL,750.0,1,28.67,1128,BROWN-FORMAN CORP,1128.0,...,119863.75,90154.51,2463.18,1006122.0,13529433.08,68601.68,-13409569.33,-1.118734e+04,0.003106,0.008859
2,63,Herradura Reposado Tequila,38.99,750mL,750.0,1,30.46,1128,BROWN-FORMAN CORP,1128.0,...,112249.22,88553.10,2190.45,1006122.0,13529433.08,68601.68,-13417183.86,-1.195303e+04,0.002761,0.008297
3,72,No. 3 London Dry Gin,34.99,750mL,750.0,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP,9165.0,...,17325.31,12626.57,369.84,1077527.0,13210613.93,68054.70,-13193288.62,-7.615038e+04,0.000435,0.001311
4,75,Three Olives Tomato Vodka,14.99,750mL,750.0,1,10.94,7245,PROXIMO SPIRITS INC.,7245.0,...,314.79,134.91,16.53,682042.0,7588029.90,38994.78,-7587715.11,-2.410405e+06,0.000031,0.000041
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12256,44917,Ferreira 10-Yr Tawny Port,24.99,750mL,750.0,2,16.55,90024,VINILANDIA USA,90024.0,...,24.99,24.99,0.11,59428.0,548855.37,2802.64,-548830.38,-2.196200e+06,0.000017,0.000046
12257,44944,Sanford Santa Rita Pnt Nr,22.99,750mL,750.0,2,14.93,4425,MARTIGNETTI COMPANIES,4425.0,...,26047.67,11747.89,126.38,2640411.0,27861690.02,144929.24,-27835642.35,-1.068642e+05,0.000429,0.000935
12258,45016,Neal One Lane Bridg Cab Svgn,93.99,750mL,750.0,2,61.43,10754,PERFECTA WINES,10754.0,...,187.98,187.98,0.22,553116.0,5665501.53,28720.52,-5665313.55,-3.013785e+06,0.000004,0.000033
12259,46011,Folonari Pnt Nr Venezie,12.99,1500ml,1500.0,2,8.90,9744,FREDERICK WILDMAN & SONS,9744.0,...,51.96,25.98,0.90,70932.0,759449.24,3999.93,-759397.28,-1.461504e+06,0.000056,0.000068
12260,46964,Calera Viognier Mt Harlan,35.99,750mL,750.0,2,24.32,10754,PERFECTA WINES,10754.0,...,143.96,71.98,0.44,553116.0,5665501.53,28720.52,-5665357.57,-3.935369e+06,0.000007,0.000025

In [78]:
vendor_sales_summary.to_sql(
    "vendor_sales_summary",
    conn,
    if_exists="replace",
    index=False
)

10692